### ISSUE TITLE
Not showing any calls

### ISSUE THREAD

**Issue by TimoChr** [paviro/MMM-FRITZ-Box-Callmonitor#33]
Hi,

I believe I configured the module correctly. Unfortunately it's not showing any calls.  As I still have 'debug' switched on I see the following in the console:

Connecting socket for: MMM-FRITZ-Box-Callmonitor
Starting module: MMM-FRITZ-Box-Callmonitor
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Received config for MMM-FRITZ-Box-Callmonitor
MMM-FRITZ-Box-Callmonitor is waiting for incoming calls.
Starting access to FRITZ!Box...
Whoops! There was an uncaught exception...
SyntaxError: Unexpected token F in JSON at position 2
    at JSON.parse (<anonymous>)
    at PythonShell.asJson (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:350:21)
    at /home/pi/MagicMirror/modules/node_modules/python-shell/index.js:302:42
    at Array.forEach (<anonymous>)
    at PythonShell.recieveInternal (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:298:15)
    at PythonShell.receiveStderr (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:282:21)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:100:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Whoops! There was an uncaught exception...
TypeError: Cannot read property 'indexOf' of undefined
    at PythonShell._endCallback (/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/node_helper.js:233:25)
    at terminateIfNeeded (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:140:39)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/node_modules/python-shell/index.js:113:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

My config files looks like this:

          },
                {
                        module: 'MMM-FRITZ-Box-Callmonitor',
                        position: 'top_center', // This can be any of the regions. Best results in left or right regions.
                        header: "Kürzliche Anrufe", // This is optional
                        config: {
                                username: "iobroker",
                                password: "********",
                                fritzIP: "192.168.188.1",
                                vCard: "/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/contacts.vcf",
                                showContactsStatus: true,
                                debug: true
                                }
                },

Any hints or tipps are welcome.

Regards,
Timo

**Comment by TimoChr** [comment]
please ignore
