### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by RhodanBull** [paviro/MMM-FRITZ-Box-Callmonitor#43]
Hello.
I get the following error if i try to use the modul with the API.

Tbh i don´t know what is even meant by it.

TypeError: PythonShell is not a constructor
    at Class.loadDataFromAPI (/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/node_helper.js:216:17)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/node_helper.js:69:9)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:112:11)
    at Socket.emit (events.js:210:5)
    at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:423:28
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Best regards
RhodanBull

**Comment by RhodanBull** [comment]
Issue #32 was the same.
I am sorry for opening
